# Generated by Django 4.2.19 on 2025-04-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
