# Generated by Django 4.2.19 on 2025-04-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0002_alter_developer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('python_developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='MainAp.developer')),
            ],
        ),
    ]
