# Generated by Django 4.2.19 on 2025-04-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0003_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='skills',
        ),
    ]
