# Generated by Django 4.2.19 on 2025-04-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Python', 'Python'), ('Backend Django', 'Django'), ('Frontend', 'Frontend'), ('Git', 'Git'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('NLP', 'Natural Language Processing'), ('Computer Vision', 'Computer Vision'), ('Data Analysis', 'Data Analysis'), ('AWS', 'AWS'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Linux', 'Linux')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='MainAp.skill'),
        ),
    ]
