# Generated by Django 4.2.19 on 2025-04-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0006_skill_developer_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=150),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='developer',
            name='skills',
            field=models.TextField(default='Python, Django, frontend, Git, Machine Learning, Deep Learning, Natural Language Processing, Computer Vision, Data Analysis, AWS, Docker, Kubernetes, Linux'),
        ),
    ]
