# Generated by Django 4.2.19 on 2025-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0007_remove_contact_phone_number_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='skills',
            field=models.TextField(default='[\n    "Python.",\n    "Django.",\n    "frontend.",\n    "Git.",\n    "Machine Learning.",\n    "Deep Learning.",\n    "Natural Language Processing.",\n    "Computer Vision.",\n    "Data Analysis.",\n    "AWS.",\n    "Docker.",\n    "Kubernetes.",\n    "Linux."\n    ]'),
        ),
    ]
