# Generated by Django 4.2.19 on 2025-04-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0008_alter_developer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='skills',
            field=models.TextField(default='[\n    "Python Developer.",\n    "Django Developer .",\n    "frontend Developer.",\n    "Git.",\n    "Machine Learning.",\n    "Deep Learning.",\n    "Natural Language Processing.",\n    "Computer Vision.",\n    "Data Analysis.",\n    "AWS.",\n    "Docker.",\n    "Kubernetes.",\n    "Linux."\n    ]'),
        ),
    ]
