# Generated by Django 4.2.19 on 2025-04-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAp', '0009_alter_developer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='zip_code',
            field=models.CharField(default='44417', max_length=10),
        ),
    ]
